{% set version = "0.1-0" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-dfidx
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/dfidx_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/dfidx/dfidx_{{ version }}.tar.gz
  sha256: 2ddd363301000b8e707ff3dd18daa5cf31df49e909ac42dae1428b0d7ee0eb79

build:
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-formula
    - r-dplyr
  run:
    - r-base
    - r-formula
    - r-dplyr

test:
  commands:
    - $R -e "library('dfidx')"           # [not win]
    - "\"%R%\" -e \"library('dfidx')\""  # [win]

about:
  home: https://cran.r-project.org/package=dfidx
  license: GPL-2.0-or-later
  summary: Provides extended data frames, with a special data frame column which contains two indexes, with potentially a nesting structure.
  license_family: GPL2
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2

extra:
  recipe-maintainers:
    - conda-forge/r

# Package: dfidx
# Version: 0.0-3
# Date: 2020-05-06
# Title: Indexed Data Frames
# Authors@R: person("Yves", "Croissant", role = c("aut", "cre"), email = "yves.croissant@univ-reunion.fr")
# Depends: R (>= 2.10)
# Imports: dplyr, Formula
# Suggests: knitr, rmarkdown, AER, mlogit, plm
# Description: Provides extended data frames, with a special data frame column which contains two indexes, with potentially a nesting structure.
# License: GPL (>= 2)
# URL: https://cran.r-project.org/package=dfidx
# VignetteBuilder: knitr
# RoxygenNote: 7.0.2
# Encoding: UTF-8
# NeedsCompilation: no
# Packaged: 2020-05-06 09:48:24 UTC; yves
# Author: Yves Croissant [aut, cre]
# Maintainer: Yves Croissant <yves.croissant@univ-reunion.fr>
# Repository: CRAN
# Date/Publication: 2020-05-08 15:30:05 UTC
